Handle unknown command-line arguments.

diff --git a/hello-teacher b/hello-teacher
--- a/hello-teacher
+++ b/hello-teacher
@@ -73,6 +73,12 @@ while [[ $# -gt 0 ]]; do
       usage
       exit 0
       ;;
+    *)
+      # Take care to write the error message to stderr (the '2' in '2>&1')
+      # and exit with a non-zero status.
+      #
+      echo "Unknown argument '$1'. Try --help." 2>&1
+      exit 1
   esac
   shift
 done
